name: 'Blazium Setup CLI'

description: 'Setup Blazium CLI for use with macOS, Windows, and Linux CI/CD runners.'

author: 'blazium-engine'
branding:
  icon: 'hard-drive'
  color: 'white'
inputs:
  version:
    description: 'Blazium CLI version: e.g., 0.0.13, 0.0.14, etc. Must include major, minor, and patch.'
    default: 0.0.14
  downloads-path:
    description: 'Path to download Blazium CLI to, relative to the current working directory of the action.'
    default: 'downloads'

runs:
  using: composite
  steps:
    - name: Cache Blazium CLI
      id: cache-blazium-cli
      uses: actions/cache@v3
      with:
        path: ${{ inputs.downloads-path }}/cli
        key: ${{ runner.os }}-blazium-cli-${{ inputs.version }}
    - name: Download Blazium CLI
      shell: bash
      run: |
        echo "Runner os is ${{ runner.os }}"
        if [ "${{ runner.os }}" == "Linux" ]; then
          os="linux"
        elif [ "${{ runner.os }}" == "Windows" ]; then
          os="windows"
        else
          os="darwin"
        fi
        mkdir -p ${{ inputs.downloads-path }}/cli
        if [ "${{ steps.cache-blazium-cli.outputs.cache-hit }}" != "true" ]; then
          # If os is windows, use .exe
          if [ "$os" == "windows" ]; then
            curl -L -o ${{ inputs.downloads-path }}/cli/blazium-cli.exe https://cdn.blazium.app/cli/$os/${{ inputs.version }}/blazium-cli.exe
          else
            curl -L -o ${{ inputs.downloads-path }}/cli/blazium-cli https://cdn.blazium.app/cli/$os/${{ inputs.version }}/blazium-cli
          fi
        else
          echo "Using cached Blazium CLI"
          ls ${{ inputs.downloads-path }}/cli
        fi
        file=$(ls ${{ inputs.downloads-path }}/cli)
        BLAZIUM_CLI=${{ inputs.downloads-path }}/cli/$file
        chmod +x $BLAZIUM_CLI
        echo "BLAZIUM_CLI=$BLAZIUM_CLI" >> $GITHUB_ENV
        # Add Blazium CLI to PATH
        echo "${{ inputs.downloads-path }}/cli" >> $GITHUB_PATH

    - name: Verify Blazium CLI Installation
      shell: bash
      run: |
        blazium-cli --version
        ${{ env.BLAZIUM_CLI }} --version
